#!/bin/bash

if [ "$UID" -ne "0" ]
then
  echo "Merci de lancer le script avec sudo"
  exit 
fi 

# Installation
apt install -y python3-nautilus

wget -q -O /usr/share/nautilus-python/extensions/codium-nautilus.py https://raw.githubusercontent.com/sedoo/Ubuntu_22.04_Scripts/main/codium-nautilus.py

echo ""
echo "*** Installation terminée ***"
