#!/bin/bash

if [ "$UID" -ne "0" ]
then
  echo "Merci de lancer le script avec sudo"
  exit 
fi 

# Ajout clé & dépot
wget -nv https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_22.04/Release.key -O - | apt-key add -

echo 'deb https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_22.04/ /' | tee -a /etc/apt/sources.list.d/owncloud.list

apt update

# Installation
apt install -y owncloud-client

echo ""
echo "*** Installation terminée ***"
