#!/bin/bash

if [ "$UID" -ne "0" ]
then
  echo "Merci de lancer le script avec sudo"
  exit 1
fi 

# variables
BASICS_SCRIPT_MIN_VERSION="1"

# vérifications
wget -qO - https://raw.githubusercontent.com/sedoo/Ubuntu_22.04_Scripts/main/version-check.sh | bash -s basics $BASICS_SCRIPT_MIN_VERSION || exit 1

# Ajout clé & dépot
wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | apt-key add - || exit 1

echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-6.0.list

apt update

# Installation
apt install -y mongodb-org || exit 1

# Activation service
systemctl daemon-reload || exit 1
systemctl enable mongod || exit 1
systemctl start mongod || exit 1

# Désactivation télémétrie
mongosh --eval "disableTelemetry()"

# Désactivation pub
mongosh --eval "db.disableFreeMonitoring()"

echo ""
echo "*** Installation terminée ***"
